### PR TITLE
Updated my entry

### PR DESCRIPTION
**Pull request by Varun-Kolanu**

### CODE REVIEW

**Comment by Varun-Kolanu** [comment]
Some glitch has occured. Css didn't apply to my card. Please check it

**Comment by vaibhav-1508** [comment]
> Some glitch has occured. Css didn't apply to my card. Please check it 

Your div is not properly nested. Make a commit with the correction

**Comment by Varun-Kolanu** [comment]
> Your div is not properly nested. Make a commit with the correction

Yeah thank you. I have corrected it now

**Comment by EshaanAgg** [comment]
Please resolve merge conflicts.

**Comment by Varun-Kolanu** [comment]
> Please resolve merge conflicts.
Conflicts resolved

**Comment by Varun-Kolanu** [comment]
> Please resolve merge conflicts.

Conflict resolved

**Pull request merged**
