### PR TITLE
ADD my portfolio

### PR DESCRIPTION
**Pull request by shruti862**
add my portfolio

### CODE REVIEW

**Comment by EshaanAgg** [comment]
Please resolve merge conflicts.

**Comment by shruti862** [comment]
> Please resolve merge conflicts.

resolved the conflict

**Comment by EshaanAgg** [comment]
The conflicts still persist.

**Comment by shruti862** [comment]
> The conflicts still persist.

resolved the conflict again

**Comment by EshaanAgg** [comment]
Thanks @shruti862

**Pull request merged**
